### ISSUE TITLE
Compare two columns

### ISSUE THREAD

**Issue by Belkadam** [makeabledk/laravel-eloquent-status#10]
Hi,

Is there a way to compare two columns ?
Something like:
>return $query->where('total_paid' , '=' , 'total');

If not, is there a way to get my value from the query?
Something like:
>return $query->where('total_paid', '=', $query->total);

I'm open to any suggestion, thanks ;)

**Comment by rasmuscnielsen** [comment]
Hi @Belkadam 

It seems that you are looking to use Laravel's `->whereColumn()` method ([see documentation](https://laravel.com/docs/5.7/queries)).

This package is built on top of the underlying [https://github.com/makeabledk/laravel-query-kit](https://github.com/makeabledk/laravel-query-kit) which does not currently support `whereColumn`. However it is super easily extendable, and we'd be happy to accept a pull request that implements the `whereColumn` operator. I'm sure you could pretty much extend / copy-paste the `where` implementation.

Cheers

**Comment by Belkadam** [comment]
Thanks 👍
