### ISSUE TITLE
`withCount` query method only works for status method, not for checkStatus method

### ISSUE THREAD

**Issue by aaroncadrian** [makeabledk/laravel-eloquent-status#4]
I have a Retreat model with a `max_attendee_count` field.  I have an attendees table that joins Users with the Retreat.

I have the following Status class:

```
class RetreatStatus extends Status
{
    public function acceptingAttendees($query)
    {
        return $query->withCount('attendees')->havingRaw('`attendees_count` < `max_attendee_count`');
    }
}
```

The following works perfectly:
`Retreat::status(new RetreatStatus('acceptingAttendees'))->get();`

However, this code throws an exception:
```
$retreat = Retreat::find(1);
$retreat->checkStatus(new RetreatStatus('acceptingAttendees'));
```

I get the following exception:
> BadMethodCallException with message 'Method withCount does not exist.'

**Comment by rasmuscnielsen** [comment]
Hi @aaroncadrian 

Thanks taking the time to create this issue.

The `checkStatus()` uses a mocked Query Builder provided by https://github.com/makeabledk/laravel-query-kit

This implements the most common methods such as `where`, `whereIn` and supports nested closured etc. 
However unfortunately it will never be able to parse actual MySQL such as aggregates and `having`.  Make sure to checkout the QueryKit repo for better understanding of the underlying implementation.

Using a custom QueryBuilder achieves much better performance than hitting the database for each check. 
In this case your status depends on other tables / models which is a limitation of this approach.

This leaves two options if you still want to use this package for the model in question

- Consider a denormalization strategy. Ie. add a 'attendees_count' to the table that updates on each change
- Not recommended: Overwrite the `checkStatus()` on the `Retreat` model and make it hit the database. Ie: 

```php
public function checkStatus($status) 
{
    return static::status($status)->whereKey($this->getKey())->exists();
}
```
