### ISSUE TITLE
cannot use whereDate in queries

### ISSUE THREAD

**Issue by JacobBennett** [makeabledk/laravel-eloquent-status#6]
![image](https://user-images.githubusercontent.com/1517011/41994121-2059666c-7a13-11e8-948b-dd7f1b7a150e.png)

results in

![image](https://user-images.githubusercontent.com/1517011/41994141-2995ab46-7a13-11e8-90a8-91f94ffd8304.png)

Think this may belong on the other package though?

**Comment by rasmuscnielsen** [comment]
Hi @JacobBennett 

Thanks for taking the time to create this issue - and for featuring this package in the podcast too!

You're right - this is a lack of support in the underlying [makeabledk/laravel-query-kit](https://github.com/makeabledk/laravel-query-kit) package.

I've added a handful of more supported methods - `whereDate` included. Please update to `v0.4.0`.

Also checkout the [Extending QueryKiy](https://github.com/makeabledk/laravel-query-kit#extending-querykit) section of the QueryKit documentation. It's quite easy to add your own methods (even locally in your project) and I'd be happy to accept PR for any missing Laravel methods :-)
