### ISSUE TITLE
Is it possible to sort the status?

### ISSUE THREAD

**Issue by reefki** [makeabledk/laravel-eloquent-status#8]
Hi,

Such a nice package! However, do you have any idea how to sort the status using `orderBy` clause?

Thanks

**Comment by rasmuscnielsen** [comment]
Hi @reefki 

Thanks, I'm glad you're enjoying it!

I'm not quite sure what you are looking for. Could you give an example?

**Comment by reefki** [comment]
@rasmuscnielsen I have sorting options on my frontend, for attributes that have database column I could simply `$posts->orderBy('column_name', 'desc')->paginate()`. But since the statuses are defined using `scope` just wondering if I can do `$posts->orderBy('status', 'desc')->paginate()`.

**Comment by rasmuscnielsen** [comment]
@reefki 

Have you tried `Post::status(...)->orderBy('status', 'desc')->paginate()`? That should work out of the box.

Basically you are just chaining scopes as you normally would, when using the `status()` scope.

**Comment by reefki** [comment]
No, it doesn't work.

Because the `status` attribute is defined using `scope` and doesn't have a column in the database I got `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status'`

**Comment by rasmuscnielsen** [comment]
@reefki In that case you'd need to either

- Store the status in the database on model update (using the `PostStatus::guess($model)` method) and use the previous mentioned `orderBy`
- Use `Collection` sorting after retrieving posts: `Post::all()->sortBy('status')` (note: more memory intensive for larger result sets)
